# Generated by Django 5.0.7 on 2024-09-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IACONTENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=50, unique=True)),
                ('COLOR_paletas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=50, unique=True)),
                ('Nombre', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=25, unique=True)),
                ('Tpassw', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
