# Generated by Django 5.0.7 on 2024-10-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPost_01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
